[package]
name = "tiger_dataflow"
version = "0.1.0"
authors = ["natsutan <YRW03704@nifty.com>"]
edition = "2018"

[dependencies]
protobuf = { version = "~2.0", features = ["with-bytes"] }
petgraph = "*"